name: Deploy Yard to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0 # Adjust this according to your Yard project's Ruby version

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Generate Yard documentation
        run: |
          bundle exec yard doc

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          branch: gh-pages # GitHub Pages branch
          folder: doc       # Folder where Yard generates the docs (default is 'doc')
